
spring:
  datasource:
    url: jdbc:h2:mem:kermilov:bookdb
    schema: schema.sql
    data: data.sql
    initialization-mode: always
    show-sql: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
