spring:
  data:
    mongodb:
      database: books
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.spring.kermilov.books.mongock.changelog